name: clash_y
description: clash ui

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-46.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  process: ^4.2.4
  yaml: ^3.1.0
  nop_db:
    path: ../packages/nop_db
  nop_db_sqlite:
    path: ../packages/nop_db_sqlite
  nop_annotations:
    path: ../packages/nop_annotations
  utils:
    path: ../packages/utils
  useful_tools:
    path: ../packages/useful_tools
  clash_window_dll:
    path: ../packages/clash_window_dll
  provider: ^6.0.1
  http: ^0.13.4
  dio: ^4.0.4
  file: ^6.1.2
  path: ^1.8.0
  path_provider: ^2.0.7
  win32: ^2.3.1
  ffi: ^1.1.2
  json_annotation: ^4.3.0
  flutter_sticky_header: ^0.6.0
  hive: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  nop_db_gen:
    path: ../packages/nop_db_gen
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
